spring.application.name=BookTracker

# H2-Datenbank (in-memory)
spring.datasource.url=jdbc:h2:mem:booktracker
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=update

# OpenLibrary
openlibrary.api.base-url=https://openlibrary.org
openlibrary.api.connect-timeout-ms=2000
openlibrary.api.read-timeout-ms=5000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

jwt.secret=booktracker-secret-key-must-be-at-least-32-characters-long
jwt.expiration-ms=86400000