spring.datasource.url=jdbc:postgresql://db:5432/booktracker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=booktracker
spring.datasource.password=booktracker
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update